### ISSUE TITLE
"ERR! OMG There is no Visual C++ compiler installed." when installing

### ISSUE THREAD

**Issue by clarkx86** [mhsjlw/node-leveldb-mcpe#10]
When I'm attempting to install I get thrown the following error:

```ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Too lset or Visual Studio.
ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Too lset or Visual Studio.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldb-mcpe@2.0.0 install: `cmake-js compile -m`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldb-mcpe@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log ging output above.
```

Using the following installations:
- node.js v10.15.3
- CMake 3.14.0 x64
- Visual Studio 2017

Have a great day,
Clark

**Comment by clarkx86** [comment]
Sorry, this is rather cmake.js related. Increasing the version of the CMake dependency did improve my situation, but I just compiled on Ubuntu 18.04.2 and everything worked fine.

**Comment by clarkx86** [comment]
I want to get it to compile on Windows. It seems that the cmake.js dependency is outdated. Setting it to "5.1.0" (latest version as of now), detects Visual Studio, but throws a new error.
```CMake Error: Could not create named generator Visual Studio 15 2017 Win64```

**Comment by mhsjlw** [comment]
Adding `"install": "cmake-js compile -m -G\"Visual Studio 15 2017 Win64\""` to the `package.json` fixes this issue.

**Comment by pogzie** [comment]
> Sorry, this is rather cmake.js related. Increasing the version of the CMake dependency did improve my situation, but I just compiled on Ubuntu 18.04.2 and everything worked fine.

I cant seem to get this working with ubuntu 16.04. Im getting the same error. 

```
ubuntu@ubuntu:~/papyrusjs$ nodejs --version
v10.16.0
ubuntu@ubuntu:~/papyrusjs$ cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
ERR! OMG Process terminated: 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldb-mcpe@2.0.0 install: `cmake-js compile -m`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldb-mcpe@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mhsjlw** [comment]
I cannot help you without the rest of the log (it is above the message you've sent)
